version: "3.7"
services:
  nest:
    build:
      args:
        - NODE_VER=20.10.0
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/node_modules
    ports:
      - "3000:3000"

volumes:
  node_modules:
